spring.application.name=QuotationSoftwareBackend
server.port=8080

spring.data.mongodb.uri=mongodb+srv://quotationUser:quotation123@cluster0.lvswqve.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=quotation_db

spring.main.allow-circular-references=true