spring.application.name=QuotationSoftwareBackend
server.port=8080

spring.data.mongodb.uri=mongodb+srv://quotationUser:quotation123@cluster0.lvswqve.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=quotation_db

spring.main.allow-circular-references=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jadhavruchita27@gmail.com
spring.mail.password=bzdfkfuvqvpgsbnm


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

spring.devtools.restart.enabled=false

# Increase max request size to handle Base64 images (set to 50MB)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.max-http-header-size=1MB
