package com.quotation.controller;

import com.quotation.model.Invoice;

import com.quotation.repository.InvoiceRepository;
import com.quotation.service.NotificationService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/invoices")
@CrossOrigin(origins = "http://localhost:5173") // Allow React to connect
public class InvoiceController {

    @Autowired
    private InvoiceRepository invoiceRepository;
    
    @Autowired private NotificationService notificationService;

    @PostMapping("/create")
    public ResponseEntity<?> createInvoice(@RequestBody Invoice invoice) {
        // Ensure status is set to 'Sent' if not provided
        if (invoice.getStatus() == null || invoice.getStatus().isEmpty()) {
            invoice.setStatus("Sent");
        }

        String quotationId = invoice.getQuotationId();
        if (quotationId != null && !quotationId.isEmpty()) {
            List<Invoice> existingInvoices = invoiceRepository.findByQuotationId(quotationId);
            double totalAlreadyPaid = existingInvoices.stream()
                .mapToDouble(Invoice::getTotalPaidAmount)
                .sum();

            double quotationTotal = 0;
            try {
                quotationTotal = Double.parseDouble(invoice.getFinalAmount().replaceAll("[^\\d.]", ""));
            } catch (Exception e) {
                quotationTotal = 0;
            }

            double remaining = quotationTotal - totalAlreadyPaid;
            double newPayment = invoice.getTotalPaidAmount();

            if (remaining <= 0) {
                return ResponseEntity.badRequest().body(Map.of("message",
                    "This quotation is already fully paid. No more invoices can be generated."));
            }

            if (newPayment > remaining + 0.01) {
                return ResponseEntity.badRequest().body(Map.of("message",
                    "Payment amount exceeds remaining balance (₹" + String.format("%.2f", remaining) + ") for this quotation."));
            }

            invoice.setBalanceAmount(remaining - newPayment);
        }

        // Save the invoice
        Invoice savedInvoice = invoiceRepository.save(invoice);

        // -------------------------
        // Notification part
        // -------------------------
        try {
            String invNum = savedInvoice.getInvoiceNumber() != null ? savedInvoice.getInvoiceNumber() : "N/A";
            String empName = savedInvoice.getEmployeeName() != null ? savedInvoice.getEmployeeName() : "Unknown";
            String client = savedInvoice.getClientName() != null ? savedInvoice.getClientName() : "Unknown";

            Object rawAmount = savedInvoice.getFinalAmount();
            String amountStr = (rawAmount != null && !rawAmount.toString().equals("0")) 
                               ? "₹" + rawAmount.toString() 
                               : "₹0";

            String message = "Invoice " + invNum + " generated by " + empName + 
                             " for client " + client + " (" + amountStr + ")";

            // Send notification
            notificationService.createNotification(message, "ADMIN", "INVOICE");
        } catch (Exception e) {
            System.err.println("Notification failed: " + e.getMessage());
        }

        // Return response as usual
        return ResponseEntity.ok(savedInvoice);
    }

    @GetMapping("/employee/id/{empId}")
    public ResponseEntity<List<Invoice>> getInvoicesByEmployee(@PathVariable String empId) {
        List<Invoice> invoices = invoiceRepository.findByEmployeeId(empId);
        return ResponseEntity.ok(invoices);
    }

    @GetMapping("/all-invoices")
    public List<Invoice> getAllInvoices() {
        return invoiceRepository.findAll();
    }

    @GetMapping("/by-quotation/{quotationId}")
    public ResponseEntity<List<Invoice>> getInvoicesByQuotation(@PathVariable String quotationId) {
        List<Invoice> invoices = invoiceRepository.findByQuotationId(quotationId);
        return ResponseEntity.ok(invoices);
    }

    @PostMapping("/payment-summaries")
    public ResponseEntity<Map<String, Double>> getPaymentSummaries(@RequestBody List<String> quotationIds) {
        Map<String, Double> summaries = new HashMap<>();
        for (String qId : quotationIds) {
            List<Invoice> invoices = invoiceRepository.findByQuotationId(qId);
            double totalPaid = invoices.stream()
                .mapToDouble(Invoice::getTotalPaidAmount)
                .sum();
            summaries.put(qId, totalPaid);
        }
        return ResponseEntity.ok(summaries);
    }
    
 // ✅ ADD THIS: Update Invoice Status (For the Edit Button)
    @PutMapping("/update-status/{id}")
    public ResponseEntity<Invoice> updateInvoiceStatus(@PathVariable String id, @RequestBody Map<String, String> statusUpdate) {
        return invoiceRepository.findById(id).map(invoice -> {
            invoice.setStatus(statusUpdate.get("status"));
            return ResponseEntity.ok(invoiceRepository.save(invoice));
        }).orElse(ResponseEntity.notFound().build());
    }
    
    @DeleteMapping("/delete/{id}")
    public ResponseEntity<?> deleteInvoice(@PathVariable String id) {
        String cleanId = id.trim();
        System.out.println("Attempting to delete ID: [" + cleanId + "]"); 
        
        try {
            if (invoiceRepository.existsById(cleanId)) {
                invoiceRepository.deleteById(cleanId);
                System.out.println("SUCCESS: Invoice deleted.");
                // Correct way to return a JSON message in Spring Boot
                return ResponseEntity.ok().body(Map.of("message", "Deleted successfully"));
            } else {
                System.out.println("FAILURE: ID not found in MongoDB.");
                return ResponseEntity.status(404).body("Invoice not found with ID: " + cleanId);
            }
        } catch (Exception e) {
            System.err.println("Error during delete: " + e.getMessage());
            return ResponseEntity.status(500).body("Error: " + e.getMessage());
        }
    }
}