package com.quotation.service;

import com.quotation.model.Invoice;
import com.quotation.repository.InvoiceRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.*;

@Service
public class InvoiceService {

    @Autowired
    private InvoiceRepository invoiceRepository;

    @Autowired
    private NotificationService notificationService;

    // ✅ CREATE INVOICE (moved from controller)
    public Invoice createInvoice(Invoice invoice) {

        if (invoice.getStatus() == null || invoice.getStatus().isEmpty()) {
            invoice.setStatus("Sent");
        }

        String quotationId = invoice.getQuotationId();

        if (quotationId != null && !quotationId.isEmpty()) {

            List<Invoice> existingInvoices = invoiceRepository.findByQuotationId(quotationId);

            double totalAlreadyPaid = existingInvoices.stream()
                    .mapToDouble(Invoice::getTotalPaidAmount)
                    .sum();

            double quotationTotal = 0;

            try {
                quotationTotal = Double.parseDouble(
                        invoice.getFinalAmount().replaceAll("[^\\d.]", "")
                );
            } catch (Exception e) {
                quotationTotal = 0;
            }

            double remaining = quotationTotal - totalAlreadyPaid;
            double newPayment = invoice.getTotalPaidAmount();

            if (remaining <= 0) {
                throw new RuntimeException("Quotation already fully paid.");
            }

            if (newPayment > remaining + 0.01) {
                throw new RuntimeException(
                        "Payment exceeds remaining balance ₹" + String.format("%.2f", remaining)
                );
            }

            invoice.setBalanceAmount(remaining - newPayment);
        }

        Invoice savedInvoice = invoiceRepository.save(invoice);

        // ✅ Notification Logic
        try {
            String invNum = Optional.ofNullable(savedInvoice.getInvoiceNumber()).orElse("N/A");
            String empName = Optional.ofNullable(savedInvoice.getEmployeeName()).orElse("Unknown");
            String client = Optional.ofNullable(savedInvoice.getClientName()).orElse("Unknown");
            String project = Optional.ofNullable(savedInvoice.getProjectName()).orElse("General");

            double amount = savedInvoice.getTotalPaidAmount();
            String amountStr = "₹" + String.format("%.2f", amount);

            String message = "Invoice " + invNum + " generated by " + empName +
                    " for client " + client +
                    " (Project: " + project + ") - Payment Received: " + amountStr;

            notificationService.createNotification(message, "ADMIN", "INVOICE");

        } catch (Exception e) {
            System.err.println("Notification failed: " + e.getMessage());
        }

        return savedInvoice;
    }

    // ✅ GET ALL INVOICES (for CSV export 🔥)
    public List<Invoice> getAllInvoices() {
        return invoiceRepository.findAll();
    }

    // ✅ GET BY EMPLOYEE
    public List<Invoice> getInvoicesByEmployee(String empId) {
        return invoiceRepository.findByEmployeeId(empId);
    }

    // ✅ GET BY QUOTATION
    public List<Invoice> getInvoicesByQuotation(String quotationId) {
        return invoiceRepository.findByQuotationId(quotationId);
    }

    // ✅ PAYMENT SUMMARY
    public Map<String, Double> getPaymentSummaries(List<String> quotationIds) {
        Map<String, Double> summaries = new HashMap<>();

        for (String qId : quotationIds) {
            List<Invoice> invoices = invoiceRepository.findByQuotationId(qId);

            double totalPaid = invoices.stream()
                    .mapToDouble(Invoice::getTotalPaidAmount)
                    .sum();

            summaries.put(qId, totalPaid);
        }

        return summaries;
    }

    // ✅ UPDATE STATUS
    public Invoice updateInvoiceStatus(String id, String status) {
        return invoiceRepository.findById(id).map(invoice -> {
            invoice.setStatus(status);
            return invoiceRepository.save(invoice);
        }).orElseThrow(() -> new RuntimeException("Invoice not found"));
    }

    // ✅ DELETE
    public void deleteInvoice(String id) {
        if (!invoiceRepository.existsById(id)) {
            throw new RuntimeException("Invoice not found");
        }
        invoiceRepository.deleteById(id);
    }
}